version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'yarn start:dev'
    volumes:
      - .:/app/
      - /app/node_modules
    container_name: PokemonAPI
    ports:
      - 3000:3000
